[package]
name = "whatsapp_to_dupr"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
chrono = "0"
lazy_static = "1"
#skillratings = "0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"